version: "3.7"

services:
  bililive-go:
    image: ghcr.io/apricity7117/bililive-go:latest
    platform: linux/amd64
    restart: unless-stopped
    container_name: bililive-go
    volumes:
      - ./Videos:/srv/bililive
      - ./config.docker.yml:/etc/bililive-go/config.yml
    ports:
      - 8080:8080
